// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmicwjtggorunpnqjtsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtaWN3anRnZ29ydW5wbnFqdHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNzY5MDAsImV4cCI6MjA1ODg1MjkwMH0.r8LA3BcBbh5sbHahRKlNXcFbb1wFM7QuzYpODXTm6r8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);